# Generated by Django 3.1.7 on 2021-03-23 05:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='trail_class_timing',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
