# Generated by Django 3.1.7 on 2021-03-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_trail_class_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='class_conducted',
            field=models.BooleanField(default=False),
        ),
    ]
