# Generated by Django 3.1.7 on 2021-03-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_class_conducted'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='opinion',
            field=models.TextField(blank=True, default=None, max_length=2000, null=True),
        ),
    ]
